function result = verify_layout_structure(modelName, before, varargin)
%VERIFY_LAYOUT_STRUCTURE Verify that layout did not change model structure.

p = inputParser;
p.addParameter('Scope', '', @(x) ischar(x) || isstring(x));
p.addParameter('ThrowOnFail', false, @(x) islogical(x) || isnumeric(x));
p.parse(varargin{:});
opt = p.Results;

assert(isstruct(before) && isfield(before, 'schema_version'), ...
    'VerifyLayoutStructure:InvalidSnapshot', ...
    'before must be a capture_layout_structure snapshot.');

scope = char(opt.Scope);
if isempty(scope)
    scope = before.scope;
end
after = capture_layout_structure(modelName, 'Scope', scope);

result = struct( ...
    'name', 'LAYOUT_STRUCTURE_CHECK', ...
    'model', char(modelName), ...
    'scope', scope, ...
    'status', 'FAIL', ...
    'passed', false, ...
    'added_blocks', {{}}, ...
    'removed_blocks', {{}}, ...
    'added_connections', {{}}, ...
    'removed_connections', {{}}, ...
    'before', before, ...
    'after', after, ...
    'message', '');

result.added_blocks = setdiff(after.block_signatures, before.block_signatures);
result.removed_blocks = setdiff(before.block_signatures, after.block_signatures);
result.added_connections = setdiff( ...
    after.resolved_connections, before.resolved_connections);
result.removed_connections = setdiff( ...
    before.resolved_connections, after.resolved_connections);

countsMatch = before.block_count == after.block_count ...
    && before.line_count == after.line_count ...
    && before.resolved_connection_count == after.resolved_connection_count ...
    && before.unresolved_line_count == after.unresolved_line_count ...
    && before.disconnected_line_count == after.disconnected_line_count;
setsMatch = isempty(result.added_blocks) && isempty(result.removed_blocks) ...
    && isempty(result.added_connections) && isempty(result.removed_connections);

result.passed = countsMatch && setsMatch;
if result.passed
    result.status = 'PASS';
    result.message = 'Layout preserved block inventory and connectivity.';
else
    result.message = sprintf([ ...
        'Layout changed structure: blocks %d->%d, lines %d->%d, ' ...
        'resolved connections %d->%d, unresolved lines %d->%d, ' ...
        'disconnected lines %d->%d.'], ...
        before.block_count, after.block_count, ...
        before.line_count, after.line_count, ...
        before.resolved_connection_count, after.resolved_connection_count, ...
        before.unresolved_line_count, after.unresolved_line_count, ...
        before.disconnected_line_count, after.disconnected_line_count);
end

if logical(opt.ThrowOnFail) && ~result.passed
    error('AIInLoop:LayoutChangedStructure', '%s', result.message);
end
end
