function s = ai_in_loop_stage_ibr_validation_evidence(projectRoot, modelName, iterDir, snapshotDir, state, opt)
%AI_IN_LOOP_STAGE_IBR_VALIDATION_EVIDENCE  S10C handoff evidence artifact.
%   Writes ibr_validation_evidence.md/json into the iteration directory and
%   mirrors the canonical package under build/reports/validation/<model>/.

s = struct('name','S10C_IBR_VALIDATION_EVIDENCE','status','PASS', ...
    'model',char(modelName), 'report_path','', 'json_path','', ...
    'global_report_path','', 'global_json_path','');

verificationDir = fullfile(projectRoot, 'scripts', 'verification');
if exist('write_ibr_validation_evidence_plan', 'file') ~= 2
    addpath(verificationDir);
end

modelName = char(modelName);
modelPath = fullfile(projectRoot, 'build', 'generated_models', [modelName '.slx']);
fidelityPath = fullfile(iterDir, 'fidelity_decision.md');
globalDir = fullfile(projectRoot, 'build', 'reports', 'validation', modelName);
specPath = fullfile(projectRoot, char(opt.spec_path));
buildScriptPath = fullfile(projectRoot, 'scripts', [char(opt.build_fcn) '.m']);
statusPath = fullfile(iterDir, 'status.json');
snapshotAuditPath = fullfile(iterDir, 'snapshot_audit.md');
adapterContractPath = fullfile(projectRoot, 'build', 'reports', 'adapters', [modelName '.md']);
modelVerificationPath = '';
tuningReportPath = '';
sltestReportPath = '';
if isfield(state.stages, 'S7')
    modelVerificationPath = fullfile(iterDir, 'model_verification_summary.md');
    sltestReportPath = fullfile(iterDir, 'sltest_summary.md');
end
if isfield(state.stages, 'S6')
    tuningReportPath = fullfile(iterDir, 'tuning_report.md');
end
if ~isfield(state.stages, 'S10B')
    snapshotAuditPath = '';
end

limitations = sprintf(['Evidence package generated by ai_in_loop_run goal=%s. ' ...
    'Smoke-level evidence does not claim full large-disturbance, weak-grid ' ...
    'SCR matrix, or cross-fidelity validation unless those artifacts are listed.'], ...
    char(state.goal));

evidence = write_ibr_validation_evidence_plan( ...
    'CaseName', modelName, ...
    'ModelPath', modelPath, ...
    'IntendedUse', 'AI-in-loop handoff-ready IBR plant/model package', ...
    'FidelityDecision', fidelityPath, ...
    'SnapshotPath', snapshotDir, ...
    'SpecPath', specPath, ...
    'BuildScriptPath', buildScriptPath, ...
    'StatusPath', statusPath, ...
    'SnapshotAuditPath', snapshotAuditPath, ...
    'AdapterContractPath', adapterContractPath, ...
    'ModelVerificationPath', modelVerificationPath, ...
    'TuningReportPath', tuningReportPath, ...
    'SltestReportPath', sltestReportPath, ...
    'Goal', state.goal, ...
    'StudyObjective', state.study_objective, ...
    'LimitationsNote', limitations, ...
    'OutputDir', globalDir);

s.global_report_path = evidence.report_path;
s.global_json_path = evidence.json_path;
statusValues = string({evidence.sections.status});
s.pass_count = nnz(statusValues == "PASS");
s.warn_count = nnz(statusValues == "WARN");
s.missing_count = nnz(statusValues == "MISSING");
s.not_applicable_count = nnz(statusValues == "N/A");
s.report_path = fullfile(iterDir, 'ibr_validation_evidence.md');
s.json_path = fullfile(iterDir, 'ibr_validation_evidence.json');
copyfile(evidence.report_path, s.report_path);
copyfile(evidence.json_path, s.json_path);

if isfolder(snapshotDir)
    s.snapshot_report_path = fullfile(snapshotDir, 'latest_ibr_validation_evidence.md');
    s.snapshot_json_path = fullfile(snapshotDir, 'latest_ibr_validation_evidence.json');
    copyfile(s.report_path, s.snapshot_report_path);
    copyfile(s.json_path, s.snapshot_json_path);
    iRefreshSnapshotManifest(snapshotDir);
end
end


function iRefreshSnapshotManifest(snapshotDir)
manifestPath = fullfile(snapshotDir, 'snapshot_manifest.json');
if ~isfile(manifestPath)
    return
end
try
    manifest = jsondecode(fileread(manifestPath));
catch
    return
end
manifest.files = iListFiles(snapshotDir);
manifest.refreshed_at = char(datetime('now','Format','yyyy-MM-dd HH:mm:ss'));
fid = fopen(manifestPath, 'w');
if fid < 0
    return
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(manifest));
end


function files = iListFiles(folder)
d = dir(folder);
names = {};
for k = 1:numel(d)
    if ~d(k).isdir
        names{end+1} = d(k).name; %#ok<AGROW>
    end
end
files = names;
end
